# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [7]:
print('The version is {}'.format(np.__version__),end='\n\n')
print('The configuration is {}'.format(np.show_config()))

The version is 1.18.1

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manmohan.pradhan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/manmohan.pradhan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/manmohan.pradhan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\

#### 3. Create a null vector of size 10

In [18]:
my_vect=np.zeros(10)
print(my_vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [8]:
n = np.zeros((5,8))
print("%d bytes" % (n.size * n.itemsize))
m=np.array([1,2,'hello',4])
print("%d bytes" %(m.size * m.itemsize))

320 bytes
176 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [30]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [32]:
my_vect=np.zeros(10)
my_vect[4]=1
print(my_vect)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [41]:
my_vect=np.array([i for i in range(10,50)],int)
print(my_vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [42]:
my_vect[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [51]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [53]:
x=np.array([1,2,0,0,4,0],int)
for i in range(len(x)):
    if(x[i]!=0):
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [54]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [60]:
from numpy.random import rand
y=rand(3,3,3)
print(y)


[[[0.16937096 0.00903499 0.90654715]
  [0.61624252 0.27098604 0.2831207 ]
  [0.70437292 0.67164115 0.11430794]]

 [[0.75656989 0.66533224 0.77080722]
  [0.52816198 0.83500508 0.14042566]
  [0.8835176  0.53617066 0.80044432]]

 [[0.57194887 0.82007145 0.0024816 ]
  [0.25282517 0.23520845 0.38258907]
  [0.92136547 0.20357023 0.81276405]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [76]:
z=rand(10,10)
print(z)
print('The maximum value is {}' .format(np.max(z)),'The minimum value is {}'.format(np.min(z)),sep='\n')

[[0.91452425 0.7115463  0.70286355 0.50927609 0.21516896 0.80207611
  0.86877525 0.46561198 0.27147332 0.1558175 ]
 [0.56487946 0.94862651 0.91752057 0.64576732 0.49910589 0.49366329
  0.95939219 0.33828908 0.55398216 0.33161694]
 [0.61448325 0.83980933 0.99138353 0.04425268 0.81396072 0.70353623
  0.33207171 0.99424857 0.90172997 0.65775003]
 [0.80400628 0.62252453 0.45072228 0.3789946  0.10943464 0.56956048
  0.51029557 0.74643262 0.79542933 0.75527159]
 [0.7343771  0.72963325 0.91962821 0.45156226 0.75280904 0.23581994
  0.24926647 0.46256666 0.25768717 0.46721767]
 [0.46918805 0.6424801  0.37144055 0.967233   0.29979834 0.64196972
  0.59722651 0.97778928 0.03879401 0.62591714]
 [0.53651748 0.96272646 0.94581818 0.31537088 0.94795297 0.11340978
  0.31421749 0.00252999 0.80263508 0.8595617 ]
 [0.53016065 0.12246786 0.88836055 0.04093019 0.1734562  0.55334506
  0.41514547 0.52707255 0.57819365 0.27780794]
 [0.01005951 0.4048278  0.67705431 0.43388936 0.0205083  0.3397348
  0.6118715  

#### 14. Create a random vector of size 30 and find the mean value

In [77]:
random=rand(30)
print(random)
print('The mean is {}'.format(np.mean(random)))

[0.0732231  0.0068879  0.28175532 0.36014948 0.03145421 0.63255222
 0.81412266 0.71728962 0.3222687  0.57647223 0.31584664 0.33061505
 0.82322096 0.28849791 0.22401044 0.03497267 0.32712196 0.52162187
 0.74154008 0.23934998 0.95873824 0.09735209 0.51204889 0.63814475
 0.23197447 0.12940065 0.59120011 0.76285763 0.13867888 0.33344955]
The mean is 0.4018939421228761


#### 15. Create a 2d array with 1 on the border and 0 inside

In [19]:
my_arr=np.ones((5,6))
my_arr[1:-1,1:-1]=0
print(my_arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
existing=np.zeros((10,10))
existing[1:-1,1:-1]=1
print(existing)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(0 * np.nan,np.nan == np.nan,np.inf > np.nan,np.nan - np.nan,np.nan in set([np.nan]),0.3 == 3 * 0.1,sep='\n')


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [54]:
my_diag=np.diag([1,2,3,4],-1)
print(my_diag)


    

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [67]:
my_mat=np.zeros((8,8))
my_mat[1::2,::2]=1
my_mat[::2,1::2]=1
print(my_mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [83]:
print(np.unravel_index(100,(6,7,8)))
        


(1, 5, 4)
